### ISSUE TITLE
Clarify AI term usage

### ISSUE THREAD

**Issue by PieterKas** [bspk/draft-gilman-wimse-use-cases#5]
The term AI is used on line 130:

AI: Observability should be a requirement. The credential should have a meaningful identifier that can be logged etc

I don't recall the context of the AI term, but if we mean to say Artificial Intelligence, it feels a bit specific to call that out in the context of observability since this can be achieved in other was as well.

**Comment by jsalowey** [comment]
I don't recall AI being part of the discussion, but I might have filtered that out.  May its left over from an Action Item?
